version: '3'

services:
  api:
    build: server
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000

  adminer:
    image: adminer
    restart: always
    ports:
      - 5433:8080

  db:
    build: database
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432